# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=-3,
    false_easting=-195526.00000000204,
    false_northing=-5484812.999999951,
    scale_factor=0.9996,
)
