red_liveries = {'An-26B': ['Aeroflot'],
 'F-4E-45MC': ['default'],
 'F-5E': ['usa standard'],
 'F-5E-3': ['usa standard'],
 'L-39ZA': ['splinter camo desert'],
 'Mi-24V': ['standard 1'],
 'Mi-8MT': ['russia_vvs_standard'],
 'MiG-19P': ['default'],
 'MiG-21Bis': ['afghanistan (1)', 'syria (2)'],
 'MiG-27K': ['af standard'],
 'Mirage-F1EE': ['iriaf 3-6215 _ 1990-2010s desert (eq variant)'],
 'Su-17M4': ['af standard (RUS)'],
 'Su-24M': ['syrian air force'],
 'Su-25': ['field camo scheme #1 (native)']}