# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=3,
    false_easting=99376.00000000288,
    false_northing=-5636889.00000001,
    scale_factor=0.9996,
)
