# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=39,
    false_easting=282801.00000003993,
    false_northing=-3879865.9999999935,
    scale_factor=0.9996,
)
