# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=33,
    false_easting=169221.9999999585,
    false_northing=-3325312.9999999693,
    scale_factor=0.9996,
)
