# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=147,
    false_easting=238417.99999989968,
    false_northing=-1491840.000000048,
    scale_factor=0.9996,
)
