# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=57,
    false_easting=75755.99999999645,
    false_northing=-2894933.0000000377,
    scale_factor=0.9996,
)
