# DO NOT EDIT:
# This file is generated by tools/export_map_projection.py.
from dcs.terrain.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=-57,
    false_easting=147639.99999997593,
    false_northing=5815417.000000032,
    scale_factor=0.9996,
)
